version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: dependabot-updates
  ignore:
  - dependency-name: land
    versions:
    - ">= 0"
  - dependency-name: request_logger
    versions:
    - ">= 0"
